import pyodbc

conn = pyodbc.connect('DRIVER={SQL Server};SERVER=192.168.100.100;UID=sa;PWD=sunGo3telecom;DATABASE=IStandardPJ')
cur = conn.cursor()
ssql = '''
SELECT TOP 1000 [产品编号]
      ,[曾用编号]
      ,[产品规格]
      ,[中文品名]
      ,[英文品名]
      ,[产品类型]
      ,[中文说明]
      ,[英文说明]
      ,[MOQ]
      ,[内销价格]
      ,[外销价格]
      ,[交期]
      ,[厂商编号]
      ,[厂商简称]
      ,[工厂型号]
      ,[工厂产品名称]
      ,[单价]
      ,[计量单位]
      ,[Unit]
      ,[起订量]
      ,[报价日期]
      ,[海关编码]
      ,[包装方式]
      ,[外箱装量]
      ,[外箱单位]
      ,[外箱长度]
      ,[外箱宽度]
      ,[外箱高度]
      ,[体积]
      ,[毛重/个]
      ,[净重/个]
      ,[内盒尺码]
      ,[内盒装量]
      ,[内盒单位]
      ,[产品尺码]
      ,[20#装量]
      ,[40#装量]
      ,[中盒尺码]
      ,[中盒装量]
      ,[中盒单位]
      ,[产品质量]
      ,[颜色]
      ,[产品条码]
      ,[样品页码]
      ,[存储位置]
      ,[期初存样]
      ,[开发时间]
  FROM [IStandardPJ].[dbo].[Abs_PLC]
'''
cur.execute(ssql)
rs = cur.fetchall()
print(rs)